### PR TITLE
Fix failing phishing test

### PR DESCRIPTION
**Pull request by dpgraham**
This test fails on 12.1 as well as 12.2

Also, updated WDA

### CODE REVIEW

**Comment by dpgraham** [comment]
@imurchie sorry I should have labeled this a "work-in-progress"

**Comment by imurchie** [comment]
👍 No problem!

**Comment by dpgraham** [comment]
Hey @imurchie, I just checked again and it looks like the 'true' test is failing: `basics - safariIgnoreFraudWarning true should not display a phishing warning`.... here's a link to the test results: https://dev.azure.com/appiumci/Appium%20CI/_build/results?buildId=1883&view=ms.vss-test-web.build-test-results-tab

I'll try locally.

**Comment by imurchie** [comment]
Hmm. Using the junit reporter makes it difficult to see what is going on in the logs.

Can you add something to distinguish the tests, and re-run on Azure? Like
```diff
diff --git a/test/functional/helpers/session.js b/test/functional/helpers/session.js
index 8990946..8e2d14c 100644
--- a/test/functional/helpers/session.js
+++ b/test/functional/helpers/session.js
@@ -91,6 +91,13 @@ if (process.env.CLOUD) {
   });
 }

+beforeEach(function () {
+  if (process.env.CI) {
+    // small log line to distinguish in logs
+    console.log(`\n\nTest: '${this.currentTest.title}'`); // eslint-disable-line
+  }
+});
+
 async function initDriver () { // eslint-disable-line require-await
   driver = wd.promiseChainRemote(HOST, PORT);
   return driver;
```

**Comment by dpgraham** [comment]
I added multireporters (spec + junit)

```

        1) should not display a phishing warning
info HTTP --> DELETE /wd/hub/session/1ac1343a-0d63-4694-b4fd-d2ad5d23cedc
info HTTP {}
dbug MJSONWP (1ac1343a) Calling XCUITestDriver.deleteSession() with args: ["1ac1343a-0d63-4694-b4fd-d2ad5d23cedc"]
dbug XCUITest Executing command 'deleteSession'
dbug BaseDriver Event 'quitSessionRequested' logged at 1554846362149 (21:46:02 GMT+0000 (Coordinated Universal Time))
dbug WD Proxy Matched '/session/1ac1343a-0d63-4694-b4fd-d2ad5d23cedc' to command name 'deleteSession'
dbug WD Proxy Proxying [DELETE /session/1ac1343a-0d63-4694-b4fd-d2ad5d23cedc] to [DELETE http://localhost:8100/session/39A1D1B4-06C4-49A5-8726-87D43E1439BA] with no body
dbug RemoteDebugger Application 'PID:3441' disconnected. Removing from app dictionary.
dbug RemoteDebugger Current app is PID:3441
dbug RemoteDebugger No longer have app id. Attempting to find new one.
dbug RemoteDebugger Found app id key 'PID:3440' for bundle 'com.apple.mobilesafari'
dbug RemoteDebugger Application 'PID:3440' disconnected. Removing from app dictionary.
dbug RemoteDebugger Current app is PID:3440
dbug RemoteDebugger No longer have app id. Attempting to find new one.
dbug WD Proxy Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"65866E72-20D1-44F3-AE15-EB046B8F9F97\",\n  \"status\" : 0\n}"
dbug XCUITest Started background XCTest logs cleanup: find -E /private/var/folders -regex '.*/Session-WebDriverAgentRunner.*\.log$|.*/StandardOutputAndStandardError\.txt$' -type f -exec sh -c 'echo "" > "{}"' \;
info XCUITest Cleaning test logs in '/Users/vsts/Library/Developer/Xcode/DerivedData/WebDriverAgent-gzkfiypmqgicdwdmdaphofhprsnl/Logs' folder
dbug iOS Clearing log files
dbug iOS Deleting '/Users/vsts/Library/Developer/Xcode/DerivedData/WebDriverAgent-gzkfiypmqgicdwdmdaphofhprsnl/Logs'. Freeing 64K.
dbug iOS Finished clearing log files
dbug XCUITest In a web session. Removing remote debugger
dbug RemoteDebugger Disconnecting from remote debugger
dbug RemoteDebugger Cleaning up listeners
dbug BaseDriver Event 'quitSessionFinished' logged at 1554846363223 (21:46:03 GMT+0000 (Coordinated Universal Time))
dbug MJSONWP (1ac1343a) Received response: null
dbug MJSONWP (1ac1343a) But deleting session, so not returning
dbug MJSONWP (1ac1343a) Responding to client with driver.deleteSession() result: null
info HTTP <-- DELETE /wd/hub/session/1ac1343a-0d63-4694-b4fd-d2ad5d23cedc 200 1076 ms - 76
info HTTP 
```

**Comment by dpgraham** [comment]
I think it might be the site: http://malware.testing.google.test/testing/malware/*

**Pull request closed without merging**
