### PR TITLE
feat: Enable Safari settings modification for real devices

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
I got this idea after reading https://sarunw.com/posts/how-to-set-userdefaults-value-with-launch-arguments/

Basically, Safari settings are just entries in NSUserDefaults, so they could theoretically be changed via command line args, like for any other iOS or macOS app. This limits the scope for real devices in comparison to simulators, where we could change app defaults in runtime (on real devices the app must be started new to apply command line args), but something is anyway better than nothing 🎉

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Interesting to find, didn't know of that. I'll test with a real device

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Please update your local branch if you have already started the testing. I've found some issues there recently

**Comment by KazuCocoa** [comment]
Sure. I'll have time to do test tonight

**Review by KazuCocoa — APPROVED** [review]
looks good.

Tested with `safariAllowPopups` and 
```
url = "http://the-internet.herokuapp.com/redirector"
driver.get url
e = driver.find_element :css, "[target='_blank']"
e.click
```

Potentially some may not work, but at least the caps worked

**Pull request merged**
