### PR TITLE
Adjust WDA codebase so it builds on Xcode 8.2

### PR DESCRIPTION
**Pull request by imurchie**
Some recent changes in WDA make it impossible to build on Xcode 8.2 and below. But we need to do that. So remove the offending code before building.

Unfortunately none of our CI options actually run Xcode 8.2 (Travis says it does, but when you request it you get 8.3.3). Locally the tests run.

The rest of the work is cleaning up the tests a little bit.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@imurchie May I try to fix the problem on ObjectiveC level? This patching does not look very nice.

**Comment by imurchie** [comment]
Happily. I couldn't figure it out, and this is a pressing issue. If something in the WDA code could be done, this could then be removed.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/WebDriverAgent/pull/19
Please assist with testing under older Xcode

**Comment by imurchie** [comment]
Closing this in favour of #587

**Pull request closed without merging**
