### PR TITLE
fix: Update NOTCHED_DEVICE_SIZES for nativeWebTapStrict (part of #1490)

### PR DESCRIPTION
**Pull request by KazuCocoa**
This is a dummy readme update to push a new version to apply `NOTCHED_DEVICE_SIZES` update in https://github.com/appium/appium-xcuitest-driver/pull/1490 to close https://github.com/appium/appium/issues/17014

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I believe there should be a way to run release loop without adding a dummy commit. Perhaps, we can simply add a manual trigger to the above actions?

**Comment by KazuCocoa** [comment]
Maybe could be... I probably tried out the manual trigger before, but then something went wrong. Let me try manually

**Comment by KazuCocoa** [comment]
change the title, btw

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by KazuCocoa** [comment]
Hm, it seems like https://github.com/appium/appium-xcuitest-driver/blob/master/.releaserc#L6 should have `test` prefix rule to release without a dummy commit in this case even for manual trigger. So, probably we could make the `release.rc` with JS and modify it dynamically

**Pull request merged**
