### PR TITLE
Fix pixelFormat not being passed to ScreenRecorder

### PR DESCRIPTION
**Pull request by sam-viz**

### CODE REVIEW

**Comment by sam-viz** [comment]
Hello @imurchie !

Thanks for your review, when do you think it can be merged and available in Appium ?

Thank you !

**Comment by imurchie** [comment]
Well, at the very least we will have to wait for CI to finishing running.

**Comment by mykola-mokhnach** [comment]
one could also use `videoFilters` property to set pixel format and many other options

**Comment by sam-viz** [comment]
@mykola-mokhnach i didn't know that, thank you for the information ! Could be a workarround.

This PR is just for fixing the existing implementation of pixelFormat though.

**Pull request merged**
