### PR TITLE
Stop sim tests from running if it is a real device run

### PR DESCRIPTION
**Pull request by imurchie**

### CODE REVIEW

**Comment by imurchie** [comment]
Unfortunately you can't return outside a function.

**Comment by jlipps** [comment]
> Unfortunately you can't return outside a function.

Despite the fact that it's against ECMAScript rules, It appears to work just fine in Node:

```js
console.log("hi");
return;
console.log("foo");
```

prints only "hi", and no errors.

**Comment by imurchie** [comment]
Interesting. Babel doesn't like it:
```
[13:47:22] Starting 'transpile'...

/Users/isaac/code/appium-xcuitest-driver/node_modules/appium-gulp-plugins/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24
  var err = new SyntaxError(message);
            ^
SyntaxError: /Users/isaac/code/appium-xcuitest-driver/test/functional/basic/alert-e2e-specs.js: 'return' outside of function (14:2)
return;
```

**Comment by jlipps** [comment]
@imurchie ahh ok. sounds like it's not an option then. carry on!

**Pull request merged**
