### PR TITLE
Add an Xcode option to NOT treat warnings as errors while building WDA

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Just because we can :)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
We could add a condition there, like `if (!env.CI)` or something like that. I'm happy to accept any concrete proposals

**Comment by imurchie** [comment]
Hmm. I don't think we should have a check like that inside the driver code. What happens when, say, someone runs Appium in an environment where `CI` is set? We could have a variable that would be less prone to being set, but the possibility would always be there.

I'd rather a cap that defaults to having warnings be warnings. Then in our tests set it to have warnings be errors.

**Comment by mykola-mokhnach** [comment]
The count of current capabilities for xctest driver already makes me scared. Is there any other way?

**Comment by imurchie** [comment]
I know. But it's the only way we have for allowing different behaviour. In this case it could be completely undocumented, since there is no reason to use it if you are not working on Appium itself.

I guess I would not be completely opposed to an environment variable like `_APPIUM_XCUITEST_DRIVER_ERROR_ON_WARNING` or something.

**Comment by mykola-mokhnach** [comment]
@imurchie Ok, added the conditional behaviour

**Pull request merged**
