### PR TITLE
chore: Be more forgivable while pulling multiple items from the device

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Related to https://github.com/appium/appium/issues/16333

### CODE REVIEW

**Comment by KazuCocoa** [comment]
let me test this on a real device tonight.
Probably i tested only a dir case before...? mm, will test in multiple files in a folder case as well...

**Comment by mykola-mokhnach** [comment]
Thanks Kazu

**Comment by KazuCocoa** [comment]
I confirmed this pr fixed current msater's error case in pull.

**Review by KazuCocoa — APPROVED** [review]

**Comment by KazuCocoa** [comment]
i see his comment... The latest once contains only sub files/dirs when I gave `@driver.pull_folder '@com.apple.Keynote:documents/<dirname>'`...
I'll update https://appium.io/docs/en/writing-running-appium/ios/ios-xctest-file-movement/ to add such subfolder example to not forget it

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
