### PR TITLE
Switch touch endpoint to native implementation

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This PR depends on https://github.com/appium/WebDriverAgent/pull/10.
I have tested it locally and the basic stuff looks good (tap, longTap, swipe, multiple gestures, landscape/portrait). The idea is to include this change into the next beta, so Appium users have enough time to test it before it is released.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@imurchie I cannot understand why https://travis-ci.org/appium/appium-xcuitest-driver/jobs/313919845 throws `12:15  error  'errors' is not defined  no-undef` eslint error. The file `/Users/travis/build/appium/appium-xcuitest-driver/lib/commands/gesture.js` does not even include such variable. Are there some problems with source update on Travis?

**Comment by imurchie** [comment]
Now that the WDA changes are in the driver, can you rebase and repush to run the tests?

**Comment by mykola-mokhnach** [comment]
I have tested the PR with the recent beta and the following Java code:

```java
        final int startX = 200, startY = 200;
        final TouchAction ta = new TouchAction(getDriver());
        for (final long delayMs : Arrays.asList(100, 300, 500, 1000)) {
            ta.longPress(PointOption.point(startX, startY))
                    .moveTo(PointOption.point(startX + 100, startY))
                    .waitAction(waitOptions(Duration.ofMillis(delayMs)))
                    .moveTo(PointOption.point(startX + 100, startY + 100))
                    .waitAction(waitOptions(Duration.ofMillis(delayMs)))
                    .moveTo(PointOption.point(startX, startY + 100))
                    .waitAction(waitOptions(Duration.ofMillis(delayMs)))
                    .moveTo(PointOption.point(startX, startY))
                    .waitAction(waitOptions(Duration.ofMillis(delayMs)))
                    .release()
                    .perform();
        }
```

produces this result:

result

**Comment by mykola-mokhnach** [comment]
Unfortunately I was not able to test W3C actions endpoint there yet because of some compatibility issues:

```
Dec 19, 2017 4:27:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
```

**Comment by mykola-mokhnach** [comment]
@imurchie would it be possible to merge this PR to beta after 1.7.2 is published?

**Comment by imurchie** [comment]
Yes, that was my plan.

**Comment by mykola-mokhnach** [comment]
I am going to recreate this PR with the current master state.

**Pull request closed without merging**
