### PR TITLE
Add the corresponding mobile: endpoints to support multiple apps

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This PR is based on https://github.com/appium/WebDriverAgent/pull/11

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
There are integrations  tests in WDA and they pass. I don't think Appium wrapper has too much logic over it, that we need to create separate tests. It would be better if beta test team could play with it for a while.

**Comment by imurchie** [comment]
Ok. That makes sense. Are you sure they pass? Half of the integration tests do not pass in Travis, it looked like.

**Comment by mykola-mokhnach** [comment]
nah, not true, I only see 3 or 4 there and these don't pass because of known XCTest issues

**Comment by mykola-mokhnach** [comment]
Also, it would be useful to add Xcode9 to WDA tests

**Comment by imurchie** [comment]
I meant categories of integration tests. 5 out of 6 fail. If they fail for known reasons that should be in the test and the build should pass.

As for Xcode 9, go for it.

**Comment by mykola-mokhnach** [comment]
> I meant categories of integration tests. 5 out of 6 fail. If they fail for known reasons that should be in the test and the build should pass.

Fair point. I'll disable flaky tests and these with known issues in a separate PR to Appium WDA. 
BTW, don't merge with FB repository yet. The support of  Xcode SDK < 9 is broken there and all tests fail since https://github.com/facebook/WebDriverAgent/commit/e3134dbc3c5093de8ec244d92e1a79282667f2e8

**Comment by mykola-mokhnach** [comment]
@KazuCocoa I see you like to create additional wrappers for such stuff ;)

**Comment by KazuCocoa** [comment]
👍  @mykola-mokhnach 
I've created the issue to do it => https://github.com/appium/ruby_lib/issues/729
I guess I'll finish it this week.

**Pull request merged**
