### PR TITLE
Update touch actions implementation to use native endpoints

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This is a copy of https://github.com/appium/appium-xcuitest-driver/pull/546

### CODE REVIEW

**Comment by dpgraham** [comment]
@mykola-mokhnach So is this PR different from #546 or are they the same and we can close it?

**Comment by mykola-mokhnach** [comment]
No, that one I closed because there were problems with rebase. This PR is the best of the best and should be merged.

**Comment by dpgraham** [comment]
Okay, @jlipps approved the other. @jlipps do you approve this one too?

**Comment by dpgraham** [comment]
I think this can be safely merged. The CI problem was already resolved and will go away with an updated appium-base-driver version.

**Comment by mykola-mokhnach** [comment]
Ok, lets do it then.

**Pull request merged**
