### PR TITLE
Move optional dependencies back to dev

### PR DESCRIPTION
**Pull request by imurchie**
This seems like a minimal Travis config to allow tests to run on Linux but not need the full dev deps.

### CODE REVIEW

**Comment by imurchie** [comment]
Cool. The tests run fine locally on Mac. I don't have access to Linux to check it out.

**Comment by dpgraham** [comment]
I just tried doing `npm --production install` and then installing `gulp` and `appium-gulp-plugins`

The tests weren't able to run because there's other devDependencies that are needed to run the functional tests.

I could put in a fix this afternoon. Maybe a post install script that's only run if it's `dev` and `darwin`

**Comment by imurchie** [comment]
That's what this is doing:
```
npm install --no-save gulp appium-gulp-plugins chai chai-as-promised wd unzip mocha sync-request;
```
Those are the dependencies that seem to be needed.

**Comment by dpgraham** [comment]
Aha, I missed that.

**Pull request merged**
