### PR TITLE
Add class chain locator to XCUITest driver

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Add a new locator type for XCUITest-based driver. See https://github.com/facebook/WebDriverAgent/pull/442 for more details.

### CODE REVIEW

**Comment by imurchie** [comment]
Can you write up a little bit about what this is and how to use it? We will also need an issue to track getting support into clients, or else it is not usable.

**Comment by mykola-mokhnach** [comment]
@imurchie I can also create PRs for java_client (and, probably, for ruby and python clients as well). The only thing I don't like there is C# }:-)

**Comment by mykola-mokhnach** [comment]
This description can also be found at  https://github.com/facebook/WebDriverAgent/wiki/Queries

The class chain query type is similar to xpath, but can only include indexes and valid class names. Only search by direct children elements of the current element is supported. Examples of such requests:
`XCUIElementTypeWindow/XCUIElementTypeButton[3]` - select the third child button of the first child window element
`XCUIElementTypeWindow` - select all the children windows
`XCUIElementTypeWindow[2]` - select the second child window in the hierarchy. Indexing starts at 1
`XCUIElementTypeWindow/XCUIElementTypeAny[3]` - select the third child (of any type) of the first child window
`XCUIElementTypeWindow[2]/XCUIElementTypeAny `- select all the children of the second child window
`XCUIElementTypeWindow[2]/XCUIElementTypeAny[-2]` - select the second last child of the second child window
One may use '*' (star) character to substitute the universal 'XCUIElementTypeAny' class name
 
This query type has been added as a quick patch to speed up complicated xpath queries containing  many levels of nested nodes and not containing xpath function calls or attributes comparison (such locators are not recommended at all, but people still use them though)

OR 

to combine them with predicate search, since location by predicates does not respect nodes hierarchy.  For example:

The xpath locator
```
//XCUIElementTypeTable/XCUIElementTypeCell[@value='bla']
```

might be times slower than
class chain

```
XCUIElementTypeWindow/*/*/XCUIElementTypeTable[2]
```

and then apply predicate search to the previous result:

```
type == 'XCUIElementTypeCell' AND value == 'bla'
```

**Comment by imurchie** [comment]
Sounds good. Once we have client implementations we'll need to add real documentation on its usage somewhere.

**Comment by mykola-mokhnach** [comment]
@imurchie Just let me know where to add ;)

**Comment by imurchie** [comment]
I'll have to think about it! But it is not necessary until we have ways of sending in the query.

**Comment by jlipps** [comment]
great work on getting a faster xpath-like query into WDA, @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Thanks @jlipps. Also a nice piece of experience for me. It was literally implemented for the whole chain starting from WDA (ObjC) to Appium Server (NodeJS) and then Appium Java Client (java). There are also plans to do it for Python client when I have time and mood.

**Comment by jlipps** [comment]
🎉  that's fantastic

**Comment by leeyc0704** [comment]
//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name="XXX"/parent::XCUIElementTypeCell/XCUIElementTypeStaticText
can ioschain implment like the above xpath? if can ,please give a exzample, thank you very much!

**Pull request merged**
