### PR TITLE
chore: Update unit tests for setValue API

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Fixes https://travis-ci.org/appium/appium-xcuitest-driver/jobs/637502360

### CODE REVIEW

**Comment by imurchie** [comment]
Did you run these locally? I get
```
  173 passing (665ms)
  4 failing

  1) element commands
       setValue
         success
           should proxy number as array of characters:
     Error: Only strings, numbers and arrays are supported as input arguments. Received: 1234.56
      at prepareInputValue (lib/commands/element.js:119:11)
      at XCUITestDriver.setValue (lib/commands/element.js:153:14)
      at Context.<anonymous> (test/unit/commands/element-specs.js:196:22)

  2) element commands
       setValue
         success
           "after each" hook for "should proxy number as array of characters":

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/unit/commands/element-specs.js:182:40)

  3) element commands
       setValue
         failure
           should throw invalid argument exception for null:
     AssertionError: expected promise to be rejected with an error matching /supported'/ but got 'Only strings, numbers and arrays are supported as input arguments. Received: null'


  4) element commands
       setValue
         failure
           should throw invalid argument exception for object:
     AssertionError: expected promise to be rejected with an error matching /supported/ but got 'inp is not iterable'




[10:39:04] Error in plugin "gulp-mocha"
[10:39:04] Message:
[10:39:04]     There were test failures
```

**Comment by mykola-mokhnach** [comment]
Have some issues with my local npm repository, was waiting for the CI.
All good Isaac, I'm not going to merge the PR until it passes ;)

**Comment by imurchie** [comment]
The unit tests all pass on my machine, so that is great! Thanks!

**Comment by mykola-mokhnach** [comment]
Cool, thanks for checking it

**Pull request merged**
