### PR TITLE
installing device console docs

### PR DESCRIPTION
**Pull request by yaphatak**

### CODE REVIEW

**Comment by yaphatak** [comment]
@imurchie : you referenced me somewhere and I cant find that issue where someone was asking about how to build deviceconsole.

**Comment by imurchie** [comment]
Awesome! Thank you!

Any chance you've worked on something a little clearer on how to get real device testing working? People seem to be having a lot of problems. :(

**Comment by imurchie** [comment]
Shoot! I updated the README and git can't figure it out. Sorry.

**Comment by yaphatak** [comment]
@imurchie : Most of issues are coming from building `WDA`. I can write something on how to build `WDA`. I guess most of people not used to that process.

**Comment by yaphatak** [comment]
@imurchie I resolved conflicts.

**Comment by imurchie** [comment]
Thanks!

Yes. Clearly we need to have some sort of documentation telling them what the process is and how to get things going.

**Pull request merged**
