### PR TITLE
fix: Add missing return to removeApp API

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This API is expected to return a boolean true value if an app was removed successfully

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@boneskull I have no idea what TS wants from me there

**Comment by boneskull** [comment]
per appium, removeApp returns void. so appium would have to change its interface for removeApp if it is wrong.

**Comment by mykola-mokhnach** [comment]
clients expect it to return boolean and it seems like was working like that before: https://github.com/appium/java-client/issues/1888

**Review by KazuCocoa — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
> I typically don't like returning `true` on success. The more common idiom for the W3C spec is to return nothing (`null`) on success and throw an error on failure.

It should return true if the app was present on the device and was removed or false if the app was not present, so there was no need to remove it. Ofc an exception is thrown if an error occurs during removal

**Comment by mykola-mokhnach** [comment]
Eventually I don't know why this endpoint should be still in base driver. It's a driver-specific API, there is a definition for it in the local methods mapping and it must be removed from the common base driver for good

**Comment by jlipps** [comment]
It's a generic enough app related method that we kept it in base driver. Pretty much any driver would have the concept of installing or uninstalling apps. It's a good candidate for an 'appium extended w3c spec'. It's helpful to leave these in basedriver so driver authors can use something generic.

**Comment by mykola-mokhnach** [comment]
> It's a generic enough app related method that we kept it in base driver. Pretty much any driver would have the concept of installing or uninstalling apps. It's a good candidate for an 'appium extended w3c spec'. It's helpful to leave these in basedriver so driver authors can use something generic.

I have different opinion, but it's not important. The important is what should we do with the original issue? Shall I leave it as is and let the call fail for existing clients?

**Comment by jlipps** [comment]
well we should probably keep the previously working behaviour for now. this might entail changing appium base driver types, either to bring removeApp in line with previous usage, or to make it generic and allow drivers to have different response types.

**Pull request merged**
