### PR TITLE
Optimize setValue algorithm

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This fix addresses https://github.com/appium/appium/issues/7585 and also speeds up typing in general, since Appium does not execute unnecessary requests to WDA anymore

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@imurchie 

I just wanted to know if we can be a bit smarter to analyse the actual error in line 141 and only retry if the actual error code matches to the expected one (iproxy may also throw error not only because of no keyboard present)?

**Comment by imurchie** [comment]
Probably. I don't know off the top of my head what the error is when the keyboard is not up, but that could be easily parsed.

**Comment by mykola-mokhnach** [comment]
can you provide an example?

Because what I see in proxy helper is 

```javascript
  log.errorAndThrow('Proxying only works for GET, POST or DELETE requests');
...
  // temporarily handle errors that can be returned
  if (res && res.status && parseInt(res.status, 10) !== 0) {
    throw errorFromCode(res.status, res.value);
  }
```

so we can, probably, check if this error contains _status_ property to be able to distinguish it from the generic iproxy failure.

**Comment by mykola-mokhnach** [comment]
I cannot get the error code as well, because WDA manages to set the value for me even if the keyboard is not really visible on Simulator %)

Probably, we can just add log.debug there to show the error signature in logs if it happens?

**Comment by imurchie** [comment]
Weird. That's changed, then.

But sure, logging and moving on should be fine.

**Comment by mykola-mokhnach** [comment]
Ok, added logs

**Comment by imurchie** [comment]
Excellent! Thanks!

**Comment by squeemish** [comment]
I have this fix working for some of my alerts and other alerts still receive the 'Alert is obstructing view' error. Tried all combinations of setValue, sendKeys, clicking the field first and not clicking the field

Any idea why the inconsistency?

**Pull request merged**
