### PR TITLE
Note that no touch id for xcode 9

### PR DESCRIPTION
**Pull request by dpgraham**

### CODE REVIEW

**Comment by imurchie** [comment]
We **can** have it. The recent changes to make it "better" broke it. The old way still works, we just don't use it anymore.

**Comment by mykola-mokhnach** [comment]
No worries. I'll fix the script for Xcode 9. Apple has just changed menu item names there

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-ios-simulator/pull/133

**Comment by mykola-mokhnach** [comment]
I think it's not relevant anymore.

**Pull request closed without merging**
