### PR TITLE
feat: replace idevicename with the appium-ios-device api

### PR DESCRIPTION
**Pull request by umutuzgur**

### CODE REVIEW

**Comment by jlipps** [comment]
since we're starting to talk about conventional commit messages: is this actually a feature? or is it more of an internal refactor? does it provide any new features to users of this package?

**Comment by umutuzgur** [comment]
@jlipps I was also not sure about that. I don't know but I though removing a setup step is a feature but I don't have a strong opinion

**Comment by imurchie** [comment]
I would say feature. It is removing an external dependency. The new feature is not having to install and maintain `idevicename`.

**Comment by jlipps** [comment]
sounds good, i buy that.

**Pull request merged**
