### PR TITLE
Complete Safari Support

### PR DESCRIPTION
**Pull request by yaphatak**

### CODE REVIEW

**Comment by imurchie** [comment]
Is this necessary if WDA can launch Safari on its own? #171

**Comment by sugatmankar** [comment]
@yaphatak  i got this error while ./Script/bootstrap.sh

```
ERROR in ./js/app.js
Module parse failed: /Users/svc.us-q-tcoeqc-a/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Line 10: Unexpected token
You may need an appropriate loader to handle this file type.
|  */
| 
| import React from 'react';
| 
| import HTTP from 'js/http';
 @ multi main
```

what m i missing?

**Comment by imurchie** [comment]
@sugatmankar This is not the appropriate place for such queries. Please limit discussion here to the Pull Request in question.

**Comment by sugatmankar** [comment]
@imurchie my apologies for extra conversation,my automation was stucked due to ios10 upgrade .  i merged changes to my local appium as per @yaphatak and @nghiadhd suggestions ,now able to launch safari directly with the help of WDA. Now there is no safari launcher. Thanks a lot.

**Comment by imurchie** [comment]
Closing this as #171 is in.

**Pull request closed without merging**
