### PR TITLE
Make WebDriverAgent a subdirectory instead of submodule

### PR DESCRIPTION
**Pull request by dpgraham**
(@KazuCocoa this will require changes in this https://github.com/appium/WebDriverAgent/pull/167 to be copy-pasted over)

### CODE REVIEW

**Comment by imurchie** [comment]
Would all the CI be moved in this PR?

Also, I think `.gitmodules` needs to be deleted.

**Comment by dpgraham** [comment]
Arg.... yeah I forgot about CI.... that's gonna be somewhat tricky.

**Comment by KazuCocoa** [comment]
Should I wait for this PR merge if mine will be approved?

**Comment by mykola-mokhnach** [comment]
Yeah, CI needs to be updated properly, so both XCUITest and WDA tests are executed properly

**Comment by dpgraham** [comment]
@KazuCocoa no, not anymore. I'm going to have to overhaul this.

**Comment by dpgraham** [comment]
I'm going to close this for now. Going to need re-think it.

**Pull request closed without merging**
