### PR TITLE
feat: use skipSyncUiDialogTranslation option for localization on simulators

### PR DESCRIPTION
**Pull request by mwakizaka**
- add a capability named `skipSyncUiDialogTranslation`
- apply `skipSyncUiDialogTranslation` option for `mobile: configureLocalization` script
- ref: https://github.com/appium/appium/issues/19440#issuecomment-1823461012

### CODE REVIEW

**Comment by mwakizaka** [comment]
> https://github.com/appium/appium-xcuitest-driver/actions/runs/7032513364/job/19136407205?pr=2276

I assume it's not related to my change.

**Comment by KazuCocoa** [comment]
ah, this is for https://github.com/appium/appium-ios-simulator/pull/404

**Review by KazuCocoa — APPROVED** [review]
lg

**Review by KazuCocoa — APPROVED** [review]
lgtm

**Pull request merged**
