### PR TITLE
chore: cleanup the readme

### PR DESCRIPTION
**Pull request by umutuzgur**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
This should be merged after (or right before) the next stable Appium version is published, that includes the described changes

**Comment by umutuzgur** [comment]
@mykola-mokhnach What is the reason for that? Is the readme here somehow synced to the main Appium repo?

**Comment by mykola-mokhnach** [comment]
no, it it's not, but I people are still reading that. I would prefer it to be in sync with what we have in the world

**Comment by umutuzgur** [comment]
Got your point now

**Pull request merged**
