### PR TITLE
Bump up the version to 2.116.2

### PR DESCRIPTION
**Pull request by umutuzgur**

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Has not been published? cc @imurchie 
https://www.npmjs.com/package/appium-xcuitest-driver

**Comment by imurchie** [comment]
@umutuzgur The bumping of versions is done as part of the publishing process, by npm itself.

To publish a package, decide if it is a major, minor, or patch release, then run:
```
npm version <major|minor|patch>
git push --tags origin master
npm publish
```
The first step will update the version number in `package.json`, as well as creating a tag for that version.

**Comment by umutuzgur** [comment]
Sorry about that. I'm the rookie here for npm

**Comment by imurchie** [comment]
No problem!

**Pull request merged**
