### PR TITLE
createSession should return session's capabilities

### PR DESCRIPTION
**Pull request by theoden9014**
https://github.com/appium/appium-uiautomator2-driver/pull/157 for xcuitest-driver

### CODE REVIEW

**Comment by KazuCocoa** [comment]
📝 note for me.

## After
```
#<Selenium::WebDriver::Remote::W3C::Capabilities:0x007fe7129f5938
 @capabilities=
  {:proxy=>nil,
   :browser_name=>nil,
   :browser_version=>nil,
   :platform_name=>"ios",
   :page_load_strategy=>nil,
   :remote_session_id=>nil,
   :accessibility_checks=>nil,
   :profile=>nil,
   :rotatable=>nil,
   :device=>nil,
   "automationName"=>"XCUITest",
   "app"=>"path/to/app",
   "platformVersion"=>"10.3",
   "deviceName"=>"iPhone Simulator",
   "useNewWDA"=>true,
   "useJSONSource"=>true,
   "someCapability"=>"some_capability"}>
```

## Before
```
=> #<Selenium::WebDriver::Remote::W3C::Capabilities:0x007ffba41aa340
 @capabilities=
  {:proxy=>nil,
   :browser_name=>"",
   :browser_version=>nil,
   :platform_name=>"ios",
   :page_load_strategy=>nil,
   :remote_session_id=>nil,
   :accessibility_checks=>nil,
   :profile=>nil,
   :rotatable=>nil,
   :device=>nil,
   "webStorageEnabled"=>false,
   "locationContextEnabled"=>false,
   "platform"=>"MAC",
   "javascriptEnabled"=>true,
   "databaseEnabled"=>false,
   "takesScreenshot"=>true,
   "networkConnectionEnabled"=>false,
   "automationName"=>"XCUITest",
   "app"=>"path/to/app",
   "platformVersion"=>"10.3",
   "deviceName"=>"iPhone Simulator",
   "useNewWDA"=>true,
   "useJSONSource"=>true,
   "someCapability"=>"some_capability",
   "udid"=>"DED4DBAD-8E5E-4AD6-BDC4-E75CF9AD84D8"}>
```

**Comment by mykola-mokhnach** [comment]
Please fix the broken unit test

**Comment by dpgraham** [comment]
I don't think we can commit these changes. The change seems to return incomplete caps.

**Comment by imurchie** [comment]
Perhaps we need to think about _why_ `caps` is complete but `this.caps` is not. Do we not ever want access to the "extra" information after we've created the session?

**Comment by imurchie** [comment]
I'd be tempted to switching to `this.caps` throughout (i.e., once we call `super.createSession`, only deal in terms of `this.caps` and not `caps`) in every driver.

**Comment by jlipps** [comment]
Yeah, having 2 non-identical objects playing similar roles does not sound ideal

**Comment by dpgraham** [comment]
@imurchie Yeah I agree. I'm a little concerned about adding this to 1.8.0 though because I don't want to risk a breaking change.

**Comment by dpgraham** [comment]
l'll re-open anyways to keep it on the backburner

**Comment by imurchie** [comment]
Yeah. Not to be done now, and this PR breaks things because of how this driver is written.

**Comment by imurchie** [comment]
Opened an issue.

**Pull request closed without merging**
