### PR TITLE
Switch to flick utility usage for real device screen recording

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/appium/issues/11118

Special thanks to @isonic1 for making such a cool utility

Please do not merge this PR yet, as it requires some more manual testing.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I did several tests and it looks like the resulting video is not very performant. I'll give it another shot with https://github.com/openstf/ios-minicap utility

**Comment by saikrishna321** [comment]
@mykola-mokhnach I have tried ios-minicap and it does work only for the single device, if i'm not wrong. In such case when it comes to parallel tests how would this work?

**Comment by mykola-mokhnach** [comment]
did you try to set different port numbers?

**Comment by saikrishna321** [comment]
@mykola-mokhnach i tried a few months back and it didn't work. I don't have devices with me. @SrinivasanTarget can you try this ?

https://github.com/openstf/ios-minicap/issues/6

**Pull request closed without merging**
