### PR TITLE
Add IPHONEOS_DEPLOYMENT_TARGET argument to avoid “unguarded availability” warning with Xcode 8.3+

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This fixes webdriver build with Xcode 8.3+ and does not require any WDA sources modification. See https://github.com/facebook/WebDriverAgent/pull/525 for more details.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@jlipps exactly. The default WDA setting is to assume all warnings as errors (which I appreciate for public projects). And that particular warning happens if a protocol is defined as "available since VersionA", but one tries to compile the source for VersionB, which is lower than VersionA. Setting this VersionB to >= VersionA solves the thing.

**Comment by imurchie** [comment]
And this is dependent on the platform version, not the Xcode version?

**Comment by mykola-mokhnach** [comment]
In this particular case it also depends on Xcode version, since this warning has been only added to LLVM compiler after this Xcode release. But in general yes - the presence of such warning this only depends on target platform version.

**Comment by imurchie** [comment]
Cool! I'm good with this, then!

**Pull request merged**
