### PR TITLE
Make sure reset happens even if noReset is set to true

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Fixes https://github.com/appium/appium/issues/4956

Also use the correct method for checking whether the device is real or not

### CODE REVIEW

**Comment by marinat** [comment]
Hi, is it real to do same changes for ios versions < 10? As I understand this commit only for xcuitest-driver which supports only ios >=10

**Comment by guilhotarras** [comment]
I am using Appium 1.6.4 and this issue still exists

**Comment by SergheiRidico** [comment]
Appium version - 1.6.5
Simulator - iPhone 7 / 10.3
fullReset = false
noReset = true

Our application displays specific screen after the first launch only. 
- If I call resetApp() method before the test, Appium doesn't reset the app and I don't see specific screen.
- If I exclude 'noReset = true' capability, Appium will reset the app automatically before the test.

**Comment by momoDeako** [comment]
I'm on Appium 1.7.0, but I still see this issue. 
So far, I have tried: 
1: fullreset = false 
2: noReset = false
3: driver.resetApp(); 

Any suggestion is appreciated.

**Comment by ACBNair** [comment]
Per the code written in real-device-management.js [resetRealDevice], The method will return if there is no fullReset option is set. The log entries shows :

`[MJSONWP (ef6480f9)] Calling AppiumDriver.reset() with args: ["xxxxxxxxx"]
[XCUITest]   Executing command 'reset'
[BaseDriver] Event 'resetStarted' logged at 1573479118241 (Time))
[XCUITest] 	 Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1573479118241 (Time))
[BaseDriver] Resetting app mid-session
[BaseDriver] Running generic full reset
`
I didn't see this going through a reset process. Could anybody help.

I have the same issue reported above. NoReset = True and ResetAPP() does not work.

Appium - 1.14.0

**Comment by phuongtrinh92** [comment]
I'm now facing this issue on iOS, too. NoReset = True and resetApp() does not work.

Appium 1.16.0

**Pull request merged**
