### PR TITLE
Filter out zero waits from W3C actions

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This should workaround the problem from https://github.com/appium/appium/issues/11273

### CODE REVIEW

**Comment by dpgraham** [comment]
How would you handle the cases where you need one input device to be in motion and the other to hold still?

The multi-touch rotation motion, for example:

|Finger One|Finger Two|
|========|========|
|Press down|Press down|
|Do nothing |Move in a circle|
|Press up|Press Up|

**Comment by mykola-mokhnach** [comment]
There only time stamps are important. xctest requires the beginning and ending action time to be set

**Comment by dpgraham** [comment]
Okay, so if I understand correctly, the start and finish time are applied to the individual actions and it won't make a difference if a "tick" doesn't have a corresponding action because it just won't do anything for that time period.

**Comment by mykola-mokhnach** [comment]
yup, something like that

**Pull request merged**
