### PR TITLE
Add endpoints for lock/unlock

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Do not merge this PR until https://github.com/appium/WebDriverAgent/pull/21 is in

### CODE REVIEW

**Comment by imurchie** [comment]
Have you rebased the WDA change so the tests can run?

**Comment by mykola-mokhnach** [comment]
There is nothing to rebase yet. https://github.com/appium/WebDriverAgent/pull/32 is not in the bundled WDA submodule

**Comment by imurchie** [comment]
But the tests aren't going to run on the WDA change (appium/WebDriverAgent#32) until _it_ has been rebased with the WDA master, and repushed to Github.

**Comment by mykola-mokhnach** [comment]
My point is that it is better to do WDA updates in a separate PR, so we can carefully check tests and fix the stuff before it breaks our regression

**Comment by imurchie** [comment]
Yes. I agree completely.

My point is that the WDA code itself has tests, and they aren't getting run because Travis is broken. And they aren't getting run on CircleCI because they don't have the configuration code yet.

That configuration code is in master **of our WDA fork**. So the PRs need to be rebased with that and repushed so builds on CircleCI get initiated. Without that, they will not get merged because we have no idea if they work.

**Comment by mykola-mokhnach** [comment]
I'll recreate this PR. There are problems with submodule rebase

**Pull request closed without merging**
