### PR TITLE
Possible solution for multiple issues about idevicedate usage

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
@imurchie please take a look. I have tested this code with our automated framework and it seems there are no major issues there

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Sure. The task here is to prevent preemptive WDA startup by filtering out outdated log entries. The current implementation users idevicedate utility for this purpose with fallback to local machine date. The problem there is, that not all Appium users have idevice library properly updated, which causes idevicedate execution to fail. Appium cannot detect driver startup as a result, because it cannot distinguish old log entries from new old entries. 

My approach tries to solve the issue without affecting idevicedate utility. It just executes logs minitoring asynchronously before xcodebuild execution. Then catches all the output collected by log reader utility so far and treats this as old logs. Then we set shared flag, which indicates xcodebuild has already started and continue monitoring logs. This monitoring blocks main thread until there is a new log record about WDA initialisation or timeout happens (hardcoded as 2 minutes). This helps to avoid endless loop in case something happened to WDA and it cannot start properly.

**Comment by imurchie** [comment]
I haven't been able to get this working locally, with sims. It also fails in Travis (ignoring the linting problems).

**Comment by mykola-mokhnach** [comment]
That is strange :(
I'll try to make to play with it later to make the code stable on Travis

**Comment by imurchie** [comment]
Locally it hangs and for some reason I cannot even stop the process. I ended up having to kill the terminal and then use `lsof` to find and kill the dead server. Very weird.

**Comment by mykola-mokhnach** [comment]
@imurchie Hell yeah, it works on Travis now!

**Comment by imurchie** [comment]
@mykola-mokhnach I'm going to give this a shot locally, and look over what is going on.

Can you have a look, when you have time, at https://github.com/appium/appium-xcuitest-driver/pull/327 ? It is solving the problem from another angle.

**Comment by mykola-mokhnach** [comment]
Closed in favour of https://github.com/appium/appium-xcuitest-driver/pull/327

**Pull request closed without merging**
