### PR TITLE
feat: Allow registering your destination device on the developer portal

### PR DESCRIPTION
**Pull request by zcmgyu**
When you enable `allowProvisioningDeviceRegistration` in `desiredCapabilities`, it will allow xcodebuild to communicate with the Apple Developer website to automatically signed targets, xcodebuild will create and update profiles, app IDs, and certificates, register your destination device on the developer portal if necessary. Requires a developer account to have been added in Xcode's Accounts preference pane.

Related PR:  https://github.com/appium/WebDriverAgent/pull/389

### CODE REVIEW

**Comment by KazuCocoa** [comment]
appium-webdriveragent@2.23.0 is available

**Comment by KazuCocoa** [comment]
You should bump the wda module version in the package.json over 2.23 with this PR

**Comment by zcmgyu** [comment]
@KazuCocoa I bumped version to 2.23.1.

**Review by KazuCocoa — APPROVED** [review]

**Comment by ltpquang** [comment]
@KazuCocoa hi, do you have any idea when will this get integrated to `appium` main repo?

**Comment by KazuCocoa** [comment]
This pr is available in `appium@beta` or current 1.19.0 rc.

**Pull request merged**
