### PR TITLE
includes mjpegScalingFactor as xcuitest-driver settings

### PR DESCRIPTION
**Pull request by KazuCocoa**
related to https://github.com/appium/appium/issues/12771

- `DEFAULT_SETTINGS` is necessary to prevent the error message so far
- ~~Set `mjpegScalingFactor`  if it contains in capabilities~~
- ~~Add descriptions which can set as capabilities~~

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I would say this  is not needed, since we already have a universal way to set settings from capabilities (using `settings[settingName]`) cap format: https://github.com/appium/appium/pull/12440

**Comment by KazuCocoa** [comment]
ah, okay. I remember.
Adding the settings in `DEFAULT_SETTINGS` is needed since the value is used to generate the warning message

**Comment by mykola-mokhnach** [comment]
@imurchie It looks like CI is broken

**Comment by imurchie** [comment]
@mykola-mokhnach This was an npm problem. I re-ran the unit test in travis, and all the tests in Azure (https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=3217&view=logs&jobId=0a296736-6346-5e71-5081-8a9c58dece03) and all is well.

**Pull request merged**
