### PR TITLE
feat: Don't use ifuse for pushing files to the phone

### PR DESCRIPTION
**Pull request by umutuzgur**

### CODE REVIEW

**Comment by KazuCocoa** [comment]
I found a regression for this PR => https://github.com/appium/appium/issues/12983
Could you take a look?

**Comment by mykola-mokhnach** [comment]
@KazuCocoa I think it's time to remove the related binary checks from Appium Doctor

**Comment by KazuCocoa** [comment]
Yes, exactly 🚿

**Comment by imurchie** [comment]
That might wait until this stuff is released in an actual version of Appium.

**Pull request merged**
