### PR TITLE
refactor: Remove idevicescreenshot since don't need it

### PR DESCRIPTION
**Pull request by umutuzgur**
I'm suggesting removing `idevicescreenshot` if it is no longer needed

### CODE REVIEW

**Comment by umutuzgur** [comment]
Let me do a load test

**Comment by umutuzgur** [comment]
@imurchie WDA screenshot code doesn't work with iOS versions below 11. I need to fix that first apparently but then it is reliable

**Comment by imurchie** [comment]
Alrighty. Should we hold off on this until that can be done?

**Comment by mykola-mokhnach** [comment]
@umutuzgur Appium does not support Xcode8 (and iOS10, which is based on it) since quite a while.

**Comment by umutuzgur** [comment]
@imurchie Can you confirm this? I should probably communicate this internally then

**Comment by umutuzgur** [comment]
@imurchie The fix it merged in WDA. All looks good now and we can proceed with this PR

**Pull request merged**
