### PR TITLE
fix LOG_STARTTIME_REGEX for dates with single digit number

### PR DESCRIPTION
**Pull request by aluedeke**
fix for #117

### CODE REVIEW

**Comment by aluedeke** [comment]
@imurchie my personal opinion would be to not wait for log statements but ping the webdriver agent http endpoint?

**Comment by jlipps** [comment]
@aluedeke i like the idea of pinging the http server instead as well

**Comment by ssynix** [comment]
I thought appium's watching the logs because it doesn't know the address of the http server.

If there's a way to tell WDA which address/port to run on, then it'd definitely be a better solution.

**Comment by jlipps** [comment]
Yeah I haven't looked into this code, maybe there is some hard reason like that. Now that I think about it, IIRC WDA picks its own random port.

**Comment by aluedeke** [comment]
according to the following code its possible:
https://github.com/facebook/WebDriverAgent/blob/4addbcd4a3d9e5ec6241ac4ad3830227f2f4ccd4/WebDriverAgentLib/Utilities/FBConfiguration.m#L30

**Comment by aluedeke** [comment]
@jlipps any plans to merge this? if log parsing is the only alternative we have for now lets at least get rid of the parsing error. i btw have no clue why travis is complaining

**Comment by imurchie** [comment]
I will look into pinging the server, in addition to the log checks. Thanks for this fix!

**Pull request merged**
