### PR TITLE
refactor: Handle both native and Safari alerts on WDA side

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Comment by imurchie** [comment]
Any idea why this is failing in Travis? Can you add an iOS 12 web test job in Azure and see if it is just a Travis thing?

**Comment by imurchie** [comment]
This error now happens locally, too. So something is wrong.

**Comment by mykola-mokhnach** [comment]
> This error now happens locally, too. So something is wrong.
 
Which error? Travis fails because of timeout on setUrl call

**Comment by imurchie** [comment]
Seems like the alert check is too soon.

Try
```diff
--- a/test/functional/web/safari-nativewebtap-e2e-specs.js
+++ b/test/functional/web/safari-nativewebtap-e2e-specs.js
@@ -143,7 +143,7 @@ describe('Safari - coordinate conversion -', function () {
           await loadPage(driver, GUINEA_PIG_PAGE);

           await driver.elementById('alert1').click();
-          await driver.acceptAlert();
+          await retryInterval(5, 1000, driver.acceptAlert.bind(driver));
           await driver.title().should.eventually.include('I am a page title');
         });
```

**Comment by imurchie** [comment]
This is now not finding alerts asking for permission, of the sort
Simulator Screen Shot - appiumTest-C33F9E2A-D126-499E-B7EA-7EB124163596-iPhone X - 2020-03-24 at 09 09 49

Details: https://gist.github.com/imurchie/68c2ffece6fac2f8474454a2d84fe4c8

**Comment by mykola-mokhnach** [comment]
WDA 2.10.2 should have the fix

**Pull request merged**
