### PR TITLE
use appium-base-driver instead of mjsonwp/express/proxy

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Comment by jlipps** [comment]
@imurchie @Jonahss looks like xcuitest build is failing, any ideas what's up?

**Comment by imurchie** [comment]
It hasn't passed for five months, and in the moment I had to look at it, I couldn't get it to run locally. So I have no idea what the issue is.

**Comment by jlipps** [comment]
ok published as 1.0.2

**Comment by jlipps** [comment]
just kidding... don't have publish rights.

**Comment by jlipps** [comment]
ok jonah hooked me up, published

**Pull request merged**
