### PR TITLE
chore: pin deps, upgrade eslint, add renovate

### PR DESCRIPTION
**Pull request by boneskull**
**UNCLEAR IF THIS SHOULDN'T BE MERGED FOR SOME REASON**

This upgrades all ESLint-related packages, pins the deps, tweaks the CI scripts and adds support for Renovate to help manage upgrades

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1499** <a href="https://app.graphite.dev/github/pr/appium/appium-xcuitest-driver/1499" target="_blank">Graphite</a> 
    * **PR #1500** <a href="https://app.graphite.dev/github/pr/appium/appium-xcuitest-driver/1500" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium-xcuitest-driver/1500?utm_source=stack-comment).

**Review by jlipps — APPROVED** [review]
seems ok to me but we should get approval from @mykola-mokhnach or @KazuCocoa since they work on this repo a lot more

**Comment by KazuCocoa** [comment]
ah, the semantic-release module in devDependencies should be `19.0.5` for the ci failure

**Review by jlipps — APPROVED** [review]

**Review by KazuCocoa — APPROVED** [review]
lgtm

**Pull request merged**
