### PR TITLE
ensure we send back default server caps (fix appium/appium#6771)

### PR DESCRIPTION
**Pull request by jlipps**
Note that this will depend on https://github.com/appium/appium-ios-driver/pull/174 being merged and published to work.

cc @imurchie

### CODE REVIEW

**Comment by JasonLunn** [comment]
Is it weird that travis hasn't started this since this PR was created 19 hours ago?

**Comment by imurchie** [comment]
Travis' Mac cloud has been down since yesterday. They're processing the backlog now.

https://www.traviscistatus.com/

**Comment by jlipps** [comment]
once Travis goes i'll push a new version of this commit with the package.json update for ios-driver. Then we can merge directly.

**Comment by JasonLunn** [comment]
You may want to push an update now to retrigger the build, as the status page suggests that they're going to cancel all builds older than 12 hours anyway.

**Comment by jlipps** [comment]
ok, we'll see if that helps

**Comment by jlipps** [comment]
looks like the queue is still ... queueing

**Comment by imurchie** [comment]
They say the backlog will be done in 12 hours. Yikes!

**Comment by jlipps** [comment]
published as 2.0.11

**Pull request merged**
