### PR TITLE
Update WDA

### PR DESCRIPTION
**Pull request by imurchie**

### CODE REVIEW

**Comment by imurchie** [comment]
It appears something in element finding and visibility is messed up.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/22cf68c20e66c60cdf678da182f0790e26218e08/test/functional/basic/element-e2e-specs.js#L55 failed.
When I reverted https://github.com/appium/WebDriverAgent/pull/93/files , then the test passed.
Actually, the failed test's element was invisible.

The visibility is difficult... 🤔

**Comment by mykola-mokhnach** [comment]
Yes visibility detection is a pain... I don't mind if we revert that change, however there are other cases in my application under test where elements, that are actually visible, are detected as invisible.

**Comment by KazuCocoa** [comment]
Can update and apply https://github.com/appium/WebDriverAgent/pull/96 to fix this regression @imurchie

**Comment by imurchie** [comment]
Running through CI again.

**Pull request merged**
