### PR TITLE
Fix source retrieval

### LINKED ISSUE #142: driver.getPageSource() - wrong tags in returned xml
* **Appium Version:** 1.6.0-beta1 (with capability AutomationName XCUITest)
* **java-client:** 4.1.2

`driver.getPageSource()` returns xml with tags without prefix - e.g.: 
* `StaticText`
* `SegmentedControl`

When in reality the tags have `XCUIElementType` prefix - e.g.:
* `XCUIElementTypeStaticText`

Whereas `element.getTagName()` returns proper tag name (with prefix)

### PR DESCRIPTION
**Pull request by imurchie**
Fixes #142 and #150

### CODE REVIEW

**Comment by joshrlesch** [comment]
@imurchie I think this had a side effect, in that now elements that are off the screen are being returned in the `PageSource`. For example with a collapsable menu. Once the menu is closed, the element is still being returned. This leads to a problem where if there is another element with the same id that is visible, it can't be checked for visibility. The driver finds the first element and thinks its not visible.

For example, this is the cell with name `Performance Center Menu Item` that has static text of `Performance Center` is in the menu that is collapsed.
```
<XCUIElementTypeCell name="Performance Center Menu Item" label="Performance Center Menu Item" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/1/0/0/3/0/2" x="-93.75" y="119.75" width="464.25" height="66">
                                        <XCUIElementTypeStaticText name="Performance Center" label="Performance Center" value="Performance Center" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/1/0/0/3/0/2/0" x="11.25" y="137.75" width="347.25" height="30.75">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeCell>
```

This is the new page that is returned after clicking the menu item where a `Navigation Bar` has the same name `Performance Center`.
```
<XCUIElementTypeNavigationBar name="Performance Center" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/2/0/0" x="0" y="20" width="375" height="44">
                            <XCUIElementTypeImage name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2/0/0/0" x="0" y="0" width="375" height="64">
                                <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2/0/0/0/0" x="0" y="0" width="375" height="64">
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2/0/0/0/0/0" x="0" y="0" width="375" height="64">
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2/0/0/0/0/1" x="0" y="0" width="375" height="64">
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2/0/0/0/0/2" x="0" y="0" width="375" height="64">
                                    </XCUIElementTypeOther>
                                </XCUIElementTypeOther>
                                <XCUIElementTypeImage name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2/0/0/0/1" x="0" y="64" width="375" height="0.5">
                                </XCUIElementTypeImage>
                            </XCUIElementTypeImage>
                            <XCUIElementTypeButton name="icon nav openmenu" label="icon nav openmenu" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/2/0/0/1" x="5" y="24" width="55" height="33">
                            </XCUIElementTypeButton>
                            <XCUIElementTypeButton name="Back" label="Back" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2/0/0/2" x="8" y="31.5" width="21" height="21">
                            </XCUIElementTypeButton>
                            <XCUIElementTypeStaticText name="Performance Center" label="Performance Center" value="Performance Center" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/2/0/0/3" x="106.5" y="28" width="162" height="27">
                            </XCUIElementTypeStaticText>
                            <XCUIElementTypeButton name="Search Icon" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/2/0/0/4" x="329" y="27" width="30" height="30">
                            </XCUIElementTypeButton>
                        </XCUIElementTypeNavigationBar>
```

The driver finds the cell because its the first one it finds, then thinks its false. I can get around this by using xpath, but might not work for all cases. I hope this makes sense?

**Comment by imurchie** [comment]
What is being done to try to find the elements? I'm not aware of anything in the driver that depends on it.

**Comment by joshrlesch** [comment]
We are using the expected conditions in the python-client to check for visibility.

**Comment by imurchie** [comment]
I'm not sure how that is done or what it is doing.

**Comment by imurchie** [comment]
I guess the only possible solution would be to filter out non-visible elements. Not sure if this would cause more problems than it solves?

**Comment by joshrlesch** [comment]
yeah I agree with that. I guess updating lots of accessibility labels and converting to xpath is in the works. Thanks for the help

**Pull request merged**
