### PR TITLE
feat: Lock only major package versions

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
After discussing the topic with the team we have concluded it requires too much resources to review tens of PRs that renovate creates for each patch or minor package updates. Also, the change should reduce the overall size of node_modules folder by deduplicating dependencies.

### CODE REVIEW

**Comment by eglitise** [comment]
Hmm, what about leaving only the Appium-related dependencies pinned? This way if there's a hotfix needed for e.g. `appium-webdriveragent`, it won't be automatically propagated here, and a manual change would be needed every time.

**Comment by eglitise** [comment]
Worth noting that renovate is already creating PRs to pin all dependencies back, some of which are configured to be auto-merged.

**Comment by mykola-mokhnach** [comment]
I'll replace renovate with dependabot

**Comment by mykola-mokhnach** [comment]
> Hmm, what about leaving only the Appium-related dependencies pinned? Currently if there's a hotfix needed for e.g. `appium-webdriveragent`, it won't be automatically propagated here, and a manual change would be needed every time.

According to my exp if a hotfix is needed then a PR would be created anyway. PRs that are created automatically must still be merged manually, so there is no big diff in terms of effort

**Comment by eglitise** [comment]
Renovate does also merge some PRs automatically, depending on the bot configuration, like #1836 from earlier today. I think it stops the automerge only if the CI validation fails.
Arguably most (if not all) of the Appium-related dependencies here are built specifically to be integrated into other Appium modules like this one, so their changes would (or at least should) be safe to merge from the get-go. At least that's my impression.

**Pull request merged**
